packages:
  - "packages/*"
  - "apps/*"

onlyBuiltDependencies:
  - esbuild
  - "@prisma/client"
  - "@prisma/engines"
  - prisma

allowBuilds:
  esbuild: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
